CREATE TABLE ANGAJATI ( NUME NVARCHAR(100), DATA_ANGAJARE DATETIME, ID_COMPANIE INT);
INSERT INTO ANGAJATI (NUME, DATA_ANGAJARE, ID_COMPANIE) VALUES ('ANA MARIA', '1990-10-05', 1);
INSERT INTO ANGAJATI (NUME, DATA_ANGAJARE, ID_COMPANIE) VALUES ('ION IONEL', '1978-12-10', 2);
INSERT INTO ANGAJATI (NUME, DATA_ANGAJARE, ID_COMPANIE) VALUES ('MARIO IONUT', '1999-01-25', 3);

